<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AssignmentSubmissionSystem.Domain\AssignmentSubmissionSystem.Domain.csproj" />
    <ProjectReference Include="..\AssignmentSubmissionSystem.Application\AssignmentSubmissionSystem.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
